AWSTemplateFormatVersion: "2010-09-09"  
Description: "Create postgres RDS"
Resources:  
  RDSInstanceforsuperset:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceIdentifier: cfrds
      DBInstanceClass: db.t2.micro
      Engine: postgres
      MasterUsername: sahildadia
      MasterUserPassword: sahil1234567
      MultiAZ: false
      PubliclyAccessible: true