AWSTemplateFormatVersion: "2010-09-09"  
Description: "Create postgres RDS"
Resources:  
  SupersetRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceIdentifier: cfrds2
      DBInstanceClass: db.t2.micro
      Engine: postgres
      MasterUsername: sahildadia
      MasterUserPassword: sahil1234567
      MultiAZ: false
      PubliclyAccessible: true
      DBSecurityGroups:
        - !Ref SupersetRDSSG
  SupersetRDSSG:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription : Security Group for RDS public Access
      DBSecurityGroupIngress:
        - CIDRIP: 0.0.0.0/0